# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 977ab26c1d6f717de9e4cb2544461a709664951cf4f63ce1932a76b48ec173c08a0539b360978f2a2157e6180e1e2d4e723dd7182c21f97c40a057529574f013

test:
  secret_key_base: cd63cfc627b5dd95fee138b9ce7c5f7ec070631006524244a501661c7c11f1ae4aaf7aa0f509433d7213fe6461779c77982383d82eebd8f4ce50f9fe96e315af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
